using System;

namespace Question2
{
    
    class ExceptionHandle
    {
      /* static void Main(string[] args)
        {
            int c=0;
            try{
                Console.WriteLine("ENter a & b");
            int a=Convert.ToInt32(Console.ReadLine());
            int b=Convert.ToInt32(Console.ReadLine());
            c=a/b;
            int []ar={1,2,3};
            Console.WriteLine(ar[9]);
            }
            catch(FormatException)
            {
                Console.WriteLine("Format Exception");
            }
            catch(DivideByZeroException)
            {
                Console.WriteLine("Divide by 0 Exception");
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
            }
            finally{
                Console.WriteLine("Finaaly Block"+c);
            }

        }*/

    }
}
